有一4阶张量img其shape=[10, 28, 28, 3])，代表10张28*28像素的3通道RGB图像，

In [1]:
import tensorflow as tf
import numpy as np

img = tf.random_uniform([10,28,28,3])

sess = tf.Session()
print(sess.run(img))

D:\AN\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[[[0.88408303 0.55447185 0.27182496]
   [0.44296575 0.43333638 0.56900275]
   [0.7943876  0.67870176 0.05916953]
   ...
   [0.65965104 0.36501288 0.4114319 ]
   [0.8344408  0.15456736 0.00744271]
   [0.2642846  0.70062363 0.4900037 ]]

  [[0.17118716 0.95520294 0.986897  ]
   [0.36969697 0.18382502 0.25578713]
   [0.742792   0.29885828 0.20697892]
   ...
   [0.49788094 0.45773327 0.26066577]
   [0.93800545 0.14597619 0.7365359 ]
   [0.4570923  0.59082985 0.35239828]]

  [[0.42262578 0.79459167 0.01488161]
   [0.39022267 0.03985322 0.5788816 ]
   [0.6530359  0.47201443 0.23352861]
   ...
   [0.9408728  0.22125351 0.5764464 ]
   [0.15078819 0.96055245 0.8924867 ]
   [0.2625494  0.68241906 0.17394936]]

  ...

  [[0.5963638  0.23574328 0.7448119 ]
   [0.5546224  0.42552567 0.9499879 ]
   [0.2399522  0.6215838  0.04563272]
   ...
   [0.30906653 0.4548489  0.14744914]
   [0.6981816  0.87732863 0.6880379 ]
   [0.7048172  0.47099102 0.8967986 ]]

  [[0.6097295  0.9293951  0.6610621 ]
   [0.0

In [2]:
#1. 如何利用索引取出第2张图片？（注意：索引均从0开始，第二张则索引为1）
img2 = img[1]

img2.shape

TensorShape([Dimension(28), Dimension(28), Dimension(3)])

In [3]:
#2. 如何利用切片取出第2张图片？
img2_1 = tf.slice(img,[1,0,0,0],[1,28,28,3])

img2_1.shape

TensorShape([Dimension(1), Dimension(28), Dimension(28), Dimension(3)])

3. 使用切片与使用索引取出的一张图片有何不同？
区别：使用索引得到的图片的rank为3,但是使用切片得到的shape与原始数据保持一致，均为4

In [4]:
#4. 如何取出其中的第1、3、5、7张图片？
img_odd = img[0:8:2]

img_odd.shape

TensorShape([Dimension(4), Dimension(28), Dimension(28), Dimension(3)])

In [5]:
#5. 如何取出第6-8张（包括6不包括8）图片中中心区域（14*14）的部分？
img_cen = img[6:8,7:21,7:21]

img_cen.shape

TensorShape([Dimension(2), Dimension(14), Dimension(14), Dimension(3)])

In [6]:
#6. 如何将图片根据通道拆分成三份单通道图片？
path1 = tf.slice(img,[0,0,0,0],[10,28,28,1])

path2 = tf.slice(img,[0,0,0,1],[10,28,28,2])

path3 = tf.slice(img,[0,0,0,2],[10,28,28,3])

print(path1.shape)
print(path2.shape)
print(path3.shape)

(10, 28, 28, 1)
(10, 28, 28, 2)
(10, 28, 28, 3)


In [7]:
#7.写出tf.shape(img)返回的张量的阶数以及shape属性的值。
shape = tf.shape(img)

rank = tf.rank(shape) # rank is 1

sess = tf.Session()
print(sess.run(rank))

sess = tf.Session()  # result is [10 28 28 3]
print(sess.run(shape))

1
[10 28 28  3]
