1  边
    数据依赖
    控制依赖
    张量的阶、形状、数据类型

In [1]:
import tensorflow as tf
a = tf.constant([1,2])
b = tf.add([1,2],[3,4],name='op_1')
c = tf.add([1,3],[2,4],name='op_1')
d = tf.mod([1,2],[3,4],name='op_1')
e = tf.slice([1,2],[0],[1],name='123')
print(a.name)
print(b.name)
print(c.name)
print(d.name)
print(e.name)

D:\AN\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Const:0
op_1:0
op_1_1:0
op_1_2:0
123:0


In [1]:
import tensorflow as tf

D:\AN\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
b = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]],name='b')
c = tf.matmul(a,b)

d = tf.add(c,5)

with tf.Session() as sess:
    sess.run(d)
    print(d)

Tensor("Add_3:0", shape=(2, 2), dtype=float32)


控制依赖
    控制依赖是在某些操作之间没有数值上的依赖关系但执行时又需要使这些操作按照一定顺序执行，这时候我们可以声明执行顺序。
    控制依赖使用图对象的方法，返回一个可以使用上下文管理器的对象
    control_dependencies方法传入的是一个列表作为参数，列表中所包含所有被依赖的操作或张量，被依赖的所有节点可以看做是同时执行的。

In [7]:
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
b = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]],name='b')
c = tf.matmul(a,b)

g = tf.get_default_graph()
with g.control_dependencies([c]):
    d = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='d')
    e = tf.constant([[1.0,2.0],[3.0,4.0],[5.0,6.0]],name='e')
    f = tf.matmul(d,e)
    with tf.Session() as sess:
        sess.run(f)
        print(f)
    

Tensor("MatMul_7:0", shape=(2, 2), dtype=float32)


In [8]:
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], name='a')
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], name='b')
c = tf.matmul(a, b)

with tf.control_dependencies([c]):
    d = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], name='d')
    e = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], name='e')
    f = tf.matmul(d, e)
with tf.Session() as sess:
    sess.run(f)
    print(f)
    
print(c)

Tensor("MatMul_9:0", shape=(2, 2), dtype=float32)
Tensor("MatMul_8:0", shape=(2, 2), dtype=float32)


注意：有依赖的op必须写在tf.control_dependencies上下文中，否则不属于有依赖的op.

In [10]:
#错误写法
def my_fun():
    a = tf.constant(1)
    b = tf.constant(2)
    c = a + b
    
    d = tf.constant(3)
    e = tf.constant(4)
    f = a + b
    #此处f不依赖与c
    with tf.control_dependencies([c]):
        return f
    result = my_fun()

In [4]:
#获取shape的三种方法
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(a.shape)
print(a.get_shape())
print(tf.shape(a))

(2, 3)
(2, 3)
Tensor("Shape:0", shape=(2,), dtype=int32)


In [3]:
a = tf.constant([])
print(a.shape)
print(a.get_shape())

(0,)
(0,)


In [2]:
a = tf.constant(12)
print(a.shape)
print(a.get_shape())

()
()


In [18]:
a = tf.constant([[1],[2],[3]])
print(a.get_shape())

(3, 1)


In [20]:
a = tf.constant([[1,2,3],[1,2,3]])
print(tf.shape(a))
print(a.get_shape())

Tensor("Shape_2:0", shape=(2,), dtype=int32)
(2, 3)


In [22]:
a = tf.constant([[[1]],[[2]],[[3]]])
print(a.get_shape())
print(tf.shape(a))


(3, 1, 1)
Tensor("Shape_4:0", shape=(3,), dtype=int32)


In [23]:
a = tf.constant([[[1,2],[1,2]]])
print(a.get_shape())
print(tf.shape(a))

(1, 2, 2)
Tensor("Shape_5:0", shape=(3,), dtype=int32)


设计一个函数，要求实现：可以根据输入张量输出shape完成一样的元素为全1的张量。
提示，使用tf.ones函数可根据形状生成全1张量

In [9]:
import tensorflow as tf
import numpy as np
def shape_fun(s):
    a = tf.ones(s)
    print(a)
r = shape_fun([2,3])

Tensor("ones_8:0", shape=(2, 3), dtype=float32)


In [8]:
#tf.ones的用法
import tensorflow as tf
import numpy as np
a = tf.ones([2,3])

print(a)
print(a.get_shape())

Tensor("ones_7:0", shape=(2, 3), dtype=float32)
(2, 3)


张量的形状可以通过python中的列表或元祖（list或tuples）来表示，或者也可以用TensorShape对象来表示:
a.shape
a.get_shape()
tf.shape(a)

设置与获取Tensor的数据类型

In [ ]:
#设置tensor的数据类型
#方法一：Tensorflow会推断出类型为tf.float32
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])

#方法二：手动设置
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=tf.float32)

#方法三：不推荐，设置numpy类型，未来可能会不兼容
#tf.int32 == np.int32      -> True
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=np.float32)


In [13]:
#获取Tensor的数据类型
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
a.dtype

tf.float32

In [14]:
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
print(a.dtype)

<dtype: 'float32'>


In [16]:
b = tf.constant(2+3j)
print(b.dtype)

<dtype: 'complex128'>


In [17]:
c = tf.constant([True,False],tf.bool)
print(c.dtype)

<dtype: 'bool'>


注意：一个张量仅允许一种dtype存在，也就是一个张量中每一个数据的数据类型必须一致

In [18]:
#数据类型转化：使用tf.cast（）

In [21]:
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
b = tf.cast(a,tf.int16)
print(b.dtype)
print(b)
b

<dtype: 'int16'>
Tensor("Cast_2:0", shape=(2, 3), dtype=int16)


<tf.Tensor 'Cast_2:0' shape=(2, 3) dtype=int16>

In [ ]:
#有些类型利用tf.cast()是无法转化的，比如string无法转化为number类型
#注意：数字字符可以转化为数字
#tf.string_to_number(string_tensor,out_type = None,name = None)
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]],name='a')
num = tf.string_to_number(a)

In [ ]:
#实数数值类型可以使用tf.cast()方法转化为bool类型

2  节点
    变量
    张量元素运算
    张量常用运算
    张量切片和索引

图中的节点也可以称为算子，代表一个操作，一般用来表示数学运算，也可以表示数据输入的起点以及输出的终点，或者读取/写入持久变量的终点。常见的节点包括：变量、张量逐元素运算、张量变形、张量索引与切片、张量运算、检查点操作、队列和同步操作、张量控制等
当OP表示数学运算时，每一个运算都会创建一个tf.Operation对象。常见的操作比如生成一个变量或者常量，数值计算均创建tf.Operation对象

In [2]:
#变量用于存储张量，可以使用list、tensor等用来进行初始化
#例：使用纯量0进行初始化一个变量：
import tensorflow as tf
var = tf.Variable(0)
var

<tf.Variable 'Variable_1:0' shape=() dtype=int32_ref>

In [8]:
#tf.add() 两个张量对应元素相加
a = tf.add(1,2)
c = tf.add([1,2],[3,4])
b = tf.constant([1,2]) + tf.constant([3,4])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))


3
[4 6]
[4 6]


In [9]:
#tf.subtract()两个张量对应元素相减
a = tf.subtract(1,2)
b = tf.subtract([1,2],[3,4])
c = tf.constant([1,2]) - tf.constant([3,4])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    

-1
[-2 -2]
[-2 -2]


In [10]:
#tf.multiply() 两个张量对应元素相乘
a = tf.multiply(1,2)
b = tf.multiply([1,2],[3,4])
c = tf.constant([1,2]) * tf.constant([3,4])
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

2
[3 8]
[3 8]


In [11]:
#tf.scalar_mul() 一个纯量分别与张量中的每一个元素相乘
a = tf.scalar_mul(10.,tf.constant([1.,2.]))
with tf.Session() as sess:
    print(sess.run(a))

[10. 20.]


In [16]:
#tf.divide() 两个张量对应元素相除
tf.divide(1,2)

0.5

In [18]:
tf.divide(tf.constant([1,2]),tf.constant([3,4]))

<tf.Tensor 'truediv_3:0' shape=(2,) dtype=float64>

In [19]:
tf.constant([1,2]) / tf.constant([3,4])

<tf.Tensor 'truediv_4:0' shape=(2,) dtype=float64>

In [22]:
#tf.div() 两个张量对应元素相除，得到的结果，不推荐使用此方法
#tf.divide与tf.div相比前者更符合python的语义

1/2


0.5

In [24]:
tf.divide(tf.constant(1),tf.constant(2))

<tf.Tensor 'truediv_7:0' shape=() dtype=float64>

In [25]:
tf.div(1/2)

TypeError: div() missing 1 required positional argument: 'y'

In [27]:
#tf.floordiv() shape相同的两个张量对应元素相除取整数部分
a = tf.floordiv(1,2)
with tf.Session() as sess:
    print(sess.run(a))
    

0


In [28]:
b = tf.floordiv([4,3],[2,5])
with tf.Session() as sess:
    print(sess.run(b))

[2 0]


In [30]:
c = tf.constant([4,3]) // tf.constant([2,5])
with tf.Session() as sess:
    print(sess.run(c))
    

[2 0]


In [32]:
#tf.mod() shape相同的两个张量对应元素进行模运算
a = tf.mod([4,3],[2,5])
with tf.Session() as sess:
    print(sess.run(a))

[0 3]


张量常用运算
tf.matmul()    通常用来做矩阵乘法
tf.transpose()  转置张量

In [1]:
import tensorflow as tf
a = tf.constant([[1.,2.,3.],[4.,5.,6.]])

tf.matmul(a,tf.transpose(a))

D:\AN\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


<tf.Tensor 'MatMul:0' shape=(2, 2) dtype=float32>

In [ ]:
#张量切片和索引
#张量变形：将张量变成指定shape的新张量
tf.reshape(tensor,shape,name=None)
#张量的拼接：沿着某个维度对两个或多个张量进行拼接

tf.concat(values,axis,name='concat')


In [5]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[10,11,12]]
print(tf.concat([t1,t2],0))


Tensor("concat_3:0", shape=(4, 3), dtype=int32)


In [ ]:
#张量的切割：对输入的张量进行切片
tf.slice(input_,begin,size,name=None)
#这个函数的作用是从输入数据input中提取一块切片：
    #切片的尺寸是size，切片的开始位置是begin；
    #切片的尺寸size表示输出tensor的数据维度，其中size[i]表示在第i维度上面的元素；
    #开始位置begin表示切片相对于输入数据input_的每一个偏移量；
    

In [ ]:
#将张量分裂成子张量
tf.split(value,num_or_size_splits,axis=0,num=None,name='split')


In [22]:
a = tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
tf.rank(a)

<tf.Tensor 'Rank_5:0' shape=() dtype=int32>

In [1]:
import tensorflow as tf

D:\AN\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
# 1.使用变量的属性initializer进行初始化：
var = tf.Variable([1,2,3])
with tf.Session() as sess:
    sess.run(var.initializer)
    print(sess.run(var))
    

[1 2 3]


In [8]:
var1 = tf.Variable([1,2,3])
var2 = tf.Variable([1,2,3])
with tf.Session() as sess:
    sess.run(tf.variables_initializer([var1,var2]))
    print(sess.run(var1))
    print(sess.run(var2))

[1 2 3]
[1 2 3]


In [12]:
#每个OP都有name属性，可以通过属性查看name值
#返回一个什么都不做的op
op = tf.no_op(name='hello')
print(op.name)

hello
